Traceback (most recent call last):
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/leonardovaia/miniconda3/envs/ml_venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
board = Board()
strategy1 = Human()
strategy2 = AlphaBeta(2, 1)

play_game(board, strategy1, strategy2)
------------------

----- stdout -----
Human VS AlphaBeta
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m strategy1 [38;5;241m=[39m Human()
[1;32m      3[0m strategy2 [38;5;241m=[39m AlphaBeta([38;5;241m2[39m, [38;5;241m1[39m)
[0;32m----> 5[0m [43mplay_game[49m[43m([49m[43mboard[49m[43m,[49m[43m [49m[43mstrategy1[49m[43m,[49m[43m [49m[43mstrategy2[49m[43m)[49m

File [0;32m~/Documents/Inteligencia artificial/Proyecto_1/docs/main.py:26[0m, in [0;36mplay_game[0;34m(board, strategy1, strategy2)[0m
[1;32m     24[0m [38;5;28;01mif[39;00m newScore [38;5;241m==[39m score:
[1;32m     25[0m     score [38;5;241m=[39m newScore
[0;32m---> 26[0m     move [38;5;241m=[39m [43mstrategy1[49m[38;5;241;43m.[39;49m[43mnext_move[49m[43m([49m[43mboard[49m[43m)[49m
[1;32m     27[0m     board[38;5;241m.[39mmake_move(move, [38;5;241m-[39m[38;5;241m1[39m)
[1;32m     28[0m     newScore [38;5;241m=[39m board[38;5;241m.[39mget_score1(move, [38;5;241m-[39m[38;5;241m1[39m)

File [0;32m~/Documents/Inteligencia artificial/Proyecto_1/docs/strategy.py:31[0m, in [0;36mHuman.next_move[0;34m(self, board)[0m
[1;32m     30[0m [38;5;28;01mdef[39;00m [38;5;21mnext_move[39m([38;5;28mself[39m, board):
[0;32m---> 31[0m     chosenLine [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mEnter the line: [39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     32[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m chosenLine[38;5;241m.[39misdigit():
[1;32m     33[0m         [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mInvalid input. Please enter a number.[39m[38;5;124m'[39m)

File [0;32m~/miniconda3/envs/ml_venv/lib/python3.9/site-packages/ipykernel/kernelbase.py:1269[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1267[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1268[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1269[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1270[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1271[0m     [38;5;28mstr[39m(prompt),
[1;32m   1272[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1273[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1274[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1275[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

